/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yunfeng_gui_MainActivity */

#ifndef _Included_com_yunfeng_gui_MainActivity
#define _Included_com_yunfeng_gui_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yunfeng_gui_MainActivity
 * Method:    guiClick
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yunfeng_gui_MainActivity_guiClick
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
