/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yunfeng_gui_JNILib */

#ifndef _Included_com_yunfeng_gui_JNILib
#define _Included_com_yunfeng_gui_JNILib
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNI_OnLoad(JavaVM *, void *);

JNIEXPORT void JNI_OnUnload(JavaVM *, void *);
/*
 * Class:     com_yunfeng_gui_JNILib
 * Method:    nativeOnSurfaceCreated
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_yunfeng_gui_JNILib_nativeOnSurfaceCreated
        (JNIEnv *, jclass, jobject);

/*
 * Class:     com_yunfeng_gui_JNILib
 * Method:    nativeOnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_yunfeng_gui_JNILib_nativeOnSurfaceChanged
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_yunfeng_gui_JNILib
 * Method:    nativeOnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yunfeng_gui_JNILib_nativeOnDrawFrame
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
