/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yunfeng_common_jni_JNILib */

#ifndef _Included_com_yunfeng_common_jni_JNILib
#define _Included_com_yunfeng_common_jni_JNILib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yunfeng_common_jni_JNILib
 * Method:    nativeOnSurfaceCreated
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_yunfeng_common_jni_JNILib_nativeOnSurfaceCreated
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_yunfeng_common_jni_JNILib
 * Method:    nativeOnDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_yunfeng_common_jni_JNILib_nativeOnDrawFrame
        (JNIEnv *, jobject);

/*
 * Class:     com_yunfeng_common_jni_JNILib
 * Method:    nativeOnSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_yunfeng_common_jni_JNILib_nativeOnSurfaceChanged
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_yunfeng_common_jni_JNILib
 * Method:    nativeOnSensorChangedRotation
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_com_yunfeng_common_jni_JNILib_nativeOnSensorChangedRotation
        (JNIEnv *env, jclass type, jfloat x, jfloat y, jfloat z);

#ifdef __cplusplus
}
#endif
#endif
